repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ^infrastructure/cloudformation/
    -   id: check-added-large-files

-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.15.0
    hooks:
    -   id: cfn-python-lint
        files: infrastructure/cloudformation/.*\.(json|yml|yaml)$
