AWSTemplateFormatVersion: 2010-09-09
Resources:

  Artifacts:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref Artifacts