name: Register service

on:
  push:
    branches:
      - main
    paths:
      - 'pkg/email/**'
      - 'pkg/response/**'
      - 'pkg/message/register/**'
      - 'cmd/register/main.go'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.1'
      - name: Show Go version
        run: go version
      - name: Build artifacts
        run: ./scripts/build.sh -s register
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: register
          path: ./bin/register/main

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: build
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: register
          path: ./bin/register/main
      - name: Show AWS CLI version
        run: aws --version
      - name: Upload artifacts to s3
        run: ./scripts/upload.sh -s register

  promote:
    name: Promote
    runs-on: ubuntu-latest
    needs: upload
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show AWS CLI version
        run: aws --version
      - name: Promote new version
        run: ./scripts/promote.sh -s register
